//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinarkaProject.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        public int id { get; set; }
        public Nullable<int> id_animal { get; set; }
        public Nullable<int> id_vrach { get; set; }
        public Nullable<System.DateTime> date_priem { get; set; }
        public string comment { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Vrach Vrach { get; set; }
    }
}
